line.bot:
  channel-token: nmGtYJ+re7RW/h8Cxg2I8iulxg4jw4uRK/e90AvjXYUrm6n7XF6QJRIt/LoZDMM0e8w3gKRB2zFA2uRRY+g6scA6jOHjBWJvbbLJeNgqecefgSJPnxaVR3L7d0X9Q/LXcrBz7w4taEmZ5+jOzKHOrgdB04t89/1O/w1cDnyilFU=
  channel-secret: 6a139f718198a12c5dbd00b69364b0ed
  handler.path: /callback
